
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 28 16:59:52 ICT 2018
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 18;
  public static final int LT = 15;
  public static final int ELSE = 22;
  public static final int PLUS = 3;
  public static final int OR = 19;
  public static final int RBRACE = 11;
  public static final int RPAREN = 8;
  public static final int THEN = 23;
  public static final int WHILE = 25;
  public static final int SEMI = 2;
  public static final int END = 28;
  public static final int INUM = 29;
  public static final int CONSOLE = 24;
  public static final int IF = 20;
  public static final int LPAREN = 7;
  public static final int GT = 14;
  public static final int LBRACE = 10;
  public static final int ID = 31;
  public static final int BEGIN = 27;
  public static final int DO = 26;
  public static final int LSHIFT = 12;
  public static final int LTEQ = 16;
  public static final int EOF = 0;
  public static final int ELSEIF = 21;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int GTEQ = 17;
  public static final int BL = 32;
  public static final int EQEQ = 13;
  public static final int FNUM = 30;
}

