
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 28 10:53:16 ICT 2018
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int THEN = 12;
  public static final int SEMI = 2;
  public static final int WHILE = 14;
  public static final int END = 17;
  public static final int INUM = 18;
  public static final int IF = 11;
  public static final int LPAREN = 7;
  public static final int COLON = 10;
  public static final int ID = 20;
  public static final int DO = 15;
  public static final int BEGIN = 16;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 13;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int BL = 21;
  public static final int FNUM = 19;
}

